### ISSUE TITLE
bug: Ping service: Is creating pings with same port

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS#1200]
### Bug description

![image](https://user-images.githubusercontent.com/1215497/198132064-c22c2fd3-f953-4f20-98f9-6d187f575a8e.png)

### Steps to reproduce

Connect two pings and a ping360

### Primary pain point(s)

The UI does not make sense and it's not possible to know which sensor is being used 

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by Williangalvani** [comment]
that is interesting. I wonder if bridges is stopping and that is causing the port to be identified as unused.

Can you share the log file?

**Comment by patrickelectric** [comment]
It was a report from manufacture, they are going to get in touch

**Comment by ES-Alexander** [comment]
Also raised in [this forum post](https://discuss.bluerobotics.com/t/ping-sonar-altimeter-udp-port-overlap-in-blue-os/14506) - I've asked for a log.

Since it's async, I suspect the driver is likely starting to detect the next device before the previous device is counted as registered in the OS. @Williangalvani not sure if you've got some idea how to fix/avoid that.

**Comment by ES-Alexander** [comment]
This has been [raised again](https://discuss.bluerobotics.com/t/ping-sonar-altimeter-udp-port-overlap-in-blue-os/14506/5), but I've also realised a possible cause, and thought of some ideas for potentially fixing it:

>... my suspicion is that the asynchronous port searching means both device connections find the same UDP port before either of them is fully connected to it (in a race condition), and then they end up sharing the connection.
>
>That may be preventable with a well-placed sleep, or perhaps by making the port connection process raise an error if multiple connections are made to the same port, and/or treatable by adding duplicate-port detection to the ping service and making it restart relevant device connections when port sharing is detected.

**Comment by ES-Alexander** [comment]
It may also be worth just storing a set of known used ports as a blacklist, since I imagine Python's variables will update faster than a port connection does. It's more important to have unique ports than to always have the same / consistent ports, so if we use a blacklist + port connection checking then that may be sufficient.
