### ISSUE TITLE
We should delete older extensions once update is done

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS#2326]
The system is not being cleaned, when updating a extension to a newer version we should delete the previous one

**Comment by ES-Alexander** [comment]
We definitely need a mechanism for deleting old extension images, but from a "you own what you've paid for" perspective I think users should be given a choice whether they want to (since they may not be able to download them again if the developer has removed the version from hosting), instead of it being forcibly automatic, and they should also be able to roll back to old versions at will (like we allow for the core image with VersionChooser).

**Comment by Williangalvani** [comment]
I guess the issue is here:

https://github.com/bluerobotics/BlueOS/blob/master/core/services/kraken/kraken.py#L197-L210

we should do remove(..., True) in order to delete. but we have to do it only after we confirm the pull was successful

**Comment by patrickelectric** [comment]
Related to #2365
