### ISSUE TITLE
logs: Save Pixhawk/Serial logs on BlueOS

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#457]
Right now Pixhawk logs are not saved on Companion, so users don't have access to it trough Log Browser.

DAYS_TO_DEVELOP:2

**Comment by patrickelectric** [comment]
@Williangalvani what is the status of this issue ? We did some telemetry changes on #1226 ?

**Comment by ES-Alexander** [comment]
I tried setting `LOG_BACKEND_TYPE` to MAVLink and seemingly got some very inconsistent behaviour from the Log Browser:

https://user-images.githubusercontent.com/25898329/212253723-b2a1eb45-9493-4b94-b057-e118aad21ee7.mov

Regardless of how well the live-stream-to-autopilot approach works, I still think it's worth the mavftp approach being implemented too, since if someone uses lots of CPU or memory for other things then maybe they don’t want to stream logs live, but they may want to be able to fetch them off the autopilot without needing to open their enclosure and access the logs via QGC.

**Comment by patrickelectric** [comment]
Already done via tlog, but will have full support to binlogs with mavftp mavftp #926
